version: '3'
services:
  mypostgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432:5432'
    volumes:
      - mypostgres:/var/lib/postgresql/data
    restart: always
volumes:
  mypostgres:
