### signup
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "admin@awc.com",
    "password": "111"
}

### signup
POST https://nestjs-boilerplate-viet.herokuapp.com/auth/signup
content-type: application/json

{
    "email": "admin@awc.com",
    "password": "111"
}

### signin
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "111@awc.com",
    "password": "111"
}

### signin prod
POST https://nestjs-boilerplate-viet.herokuapp.com/auth/signin
content-type: application/json

{
    "email": "admin@awc.com",
    "password": "111"
}

### whoami
GET http://localhost:3000/auth/whoami

### sign out
POST http://localhost:3000/auth/signout

### find user
GET http://localhost:3000/auth/1

### find user
GET http://localhost:3000/auth?email=ada@awc

### delete user
DELETE http://localhost:3000/auth/12211

### patch user
PATCH http://localhost:3000/auth/222
content-type: application/json

{
    "email": "11@awc.com"
}

### singin user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "ada@awc.com",
    "password": "adwwad"
}